# Generated by Django 5.2.6 on 2025-09-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpieza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='tareas/')),
            ],
        ),
        migrations.AlterField(
            model_name='limpieza',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='limpieza',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limpieza',
            name='tareas',
            field=models.ManyToManyField(blank=True, to='limpieza.tarealimpieza'),
        ),
    ]
