# Generated by Django 5.2.6 on 2025-09-30 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpieza', '0002_tarealimpieza_alter_limpieza_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='zonas/')),
            ],
        ),
        migrations.CreateModel(
            name='TareaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('foto', models.ImageField(upload_to='tareas/')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='limpieza.zona')),
            ],
        ),
    ]
