# Generated by Django 5.2.6 on 2025-10-21 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpieza', '0003_zona_tareazona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareazona',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='tarealimpieza',
            name='icono',
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tareas_limpieza/'),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ZonaLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='zonas_limpieza/')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='No disponible', max_length=50)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='limpieza.zonalimpieza'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Limpieza',
        ),
        migrations.DeleteModel(
            name='TareaZona',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
