# Generated by Django 5.2.6 on 2025-10-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpieza', '0004_remove_tareazona_zona_remove_tarealimpieza_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonalimpieza',
            name='is_habitacion',
            field=models.BooleanField(default=False),
        ),
    ]
