# Generated by Django 5.2.6 on 2025-10-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpieza', '0005_zonalimpieza_is_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarealimpieza',
            name='observaciones_empleado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
