# Generated by Django 5.2.6 on 2025-09-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
