# Generated by Django 5.2.6 on 2025-09-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_puesto_empleado_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
