# Generated by Django 5.2.6 on 2025-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_empleado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
