# Generated by Django 5.2.6 on 2025-10-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('personal', '0006_puesto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.rol'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
