# Generated by Django 5.2.6 on 2025-10-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_empleado_rol_delete_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
    ]
