# Generated by Django 5.2.5 on 2025-09-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('canal', models.CharField(max_length=50)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.estado')),
            ],
        ),
    ]
