# Generated by Django 5.2.5 on 2025-10-20 20:55

import django.db.models.deletion
import django.utils.timezone
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido_html', models.TextField(help_text='Puedes usar HTML aquí')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=marketing.models.upload_to)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaniamarketing',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='campaniamarketing',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='campaniamarketing',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='campaniamarketing',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='campaniamarketing',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaniamarketing',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaniamarketing',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='campaniamarketing',
            name='contactos',
            field=models.ManyToManyField(to='marketing.contactomarketing'),
        ),
        migrations.AddField(
            model_name='campaniamarketing',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.plantillamarketing'),
        ),
    ]
