# Generated by Django 5.2.5 on 2025-10-20 21:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contactomarketing_plantillamarketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamarketing',
            name='contenido_html',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='plantillamarketing',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plantillamarketing',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='plantillas/'),
        ),
        migrations.AlterField(
            model_name='plantillamarketing',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
