# Generated by Django 5.2.6 on 2025-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cierre', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cierre', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contabilidad',
            name='reserva',
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=20),
        ),
    ]
