# Generated by Django 5.2.5 on 2025-11-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FechaReservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Fechas Reservadas',
            },
        ),
        migrations.CreateModel(
            name='PrecioHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Precios de Habitaciones',
            },
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='desayuno_incluido',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='canal_reserva',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(default='habitacion', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.habitacion'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['habitacion', 'fecha_inicio', 'fecha_fin'], name='reservas_re_habitac_6c2f63_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente'], name='reservas_re_cliente_e986e9_idx'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='amenidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones', to='reservas.amenidad'),
        ),
        migrations.AddField(
            model_name='fechareservada',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_reservadas', to='reservas.habitacion'),
        ),
        migrations.AddField(
            model_name='fechareservada',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_reservadas', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='preciohabitacion',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='reservas.habitacion'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='TipoHabitacion',
        ),
        migrations.AddIndex(
            model_name='fechareservada',
            index=models.Index(fields=['habitacion', 'fecha'], name='reservas_fe_habitac_b1ec6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fechareservada',
            unique_together={('habitacion', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='preciohabitacion',
            index=models.Index(fields=['habitacion', 'fecha'], name='reservas_pr_habitac_1db8db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preciohabitacion',
            unique_together={('habitacion', 'fecha')},
        ),
    ]
