# Generated by Django 5.2.5 on 2025-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_amenidad_fechareservada_preciohabitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='amenidad',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='amenidades',
            field=models.ManyToManyField(related_name='habitaciones', to='reservas.amenidad'),
        ),
    ]
