# Generated by Django 5.2.5 on 2025-11-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_habitacion_amenidad_habitacion_amenidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='canal_reservacion',
            field=models.CharField(choices=[('sitio', 'Sitio'), ('directo', 'Directo'), ('booking', 'Booking.com'), ('airbnb', 'Airbnb')], default='sitio', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('sitio', 'Sitio')], default='sitio', max_length=20),
        ),
    ]
