# Generated by Django 5.2.5 on 2025-12-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_canal_reservacion_reserva_metodo_pago'),
        ('sitio_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sitio_web.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
