# Generated by Django 5.2.5 on 2025-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reservas_amenidad',
                'managed': False,
            },
        ),
    ]
