# Generated by Django 5.2.5 on 2025-12-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0003_cliente_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='identificacion',
        ),
    ]
