# Generated by Django 5.2.6 on 2025-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
