# Generated by Django 5.2.6 on 2025-10-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_rol_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='descripction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
