# Generated by Django 5.2.6 on 2025-10-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_rol_descripction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='descripction',
            new_name='descripcion',
        ),
    ]
