# Generated by Django 5.2.6 on 2025-10-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_rename_descripction_rol_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
