# Generated by Django 5.2.5 on 2025-10-20 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='nombre_item',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='unidad',
        ),
        migrations.AddField(
            model_name='inventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Insumo', 'Insumo')], default='Activo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
